#!/usr/bin/env sh
#
# wm independent hotkeys
#

# terminal emulator
# super + Return
# 	alacritty -e bash ~/.config/with_tmux.sh
super + Return
	kitty -e zellij

# attach to existing session
super + shift + Return
	kitty -e zellij attach --index 0 -c
	
# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
	bspc node -s biggest.local
#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focusp
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# move the node to another monitor
super + {less,greater}
	bspc node -m {west,east} --follow

# focus the node for the given path jump
# super + {p,b,comma,period}
# 	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
alt + {_,shift +}Tab
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.occupied

super + brace{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
# super + {o,i}
# 	bspc wm -h off; \
# 	bspc node {older,newer} -f; \
# 	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-5,0}
	bspc {desktop -f,node -d} '^{4-8,10}' --follow

super + {_,shift + }{6-8,10}
	bspc {desktop -f,node -d} '^{1-3}' --follow

# focus next/previous monitor
super + {_,shift + } backslash
	bspc monitor -f {next, prev}

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# rotate parent node
super + shift + r
	bspc node @parent -R 90

#
# Hide
#

# hide window
super + v
  bspc node -g hidden

# unhide window
super + shift + v
  bspc node (bspc query -N -n .hidden | tail -n1) -g hidden=off


# 
# Device control
#

# volume
XF86AudioRaiseVolume 
	amixer set Master 2%+

XF86AudioLowerVolume 
	amixer set Master 2%-

XF86AudioMute 
	amixer -D pulse set Master 1+ toggle

# brightness
XF86MonBrightnessUp
	brightnessctl set 5%+

XF86MonBrightnessDown
	brightnessctl set 5%-

# search
XF86Search
	rofi -show

# music control
XF86AudioPlay
	mpc toggle

XF86AudioPrev
	mpc prev

XF86AudioNext
	mpc next

# screenshot
Print
	shutter
# Print
# 	dunstify "hello"

#
# Application shortcut
#

super + e
	alacritty -e ranger
super + shift + e
	thunar
super + o; {d, b, p}
	{goldendict, qutebrowser, bitwarden-desktop}

# clipboard
super + c
	CM_LAUNCHER=rofi clipmenu
super + shift + d
	killall dunst;dunst &;dunstify foo

#
# rofi menus
#
# application launcher
super + @space
	rofi -show

# program launcher
super + r
	rofi -show run -theme nord-oneline

# bitwarden
super + asciitilde
	bwmenu
