#! /bin/sh
bspc monitor -d 1 2 3 4 5

bspc config border_width         5
bspc config window_gap          36

bspc config split_ratio          0.40
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config active_border_color \#81a1c1
bspc config normal_border_color \#4c566a
bspc config focused_border_color \#b48ead

bspc config top_padding 36
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 36

bspc config focus_follows_pointer false

## Rules
bspc rule -r '*:*'
bspc rule -a GoldenDict state=floating
bspc rule -a Zeal state=floating
bspc rule -a Anki state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a wechat.exe state=floating
bspc rule -a zoom state=floating
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a netease-cloud-music desktop='^5'
bspc rule -a File-roller state=floating
bspc rule -a Alacritty:scratchpad sticky=on state=floating hidden=on locked=on

## Create scratchpad
alacritty --class scratchpad -e ~/.bin/scratch
