#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d home www dev edt play
bspc monitor DP1 -d ref note chat

bspc config border_width         8
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# Send to home
bspc rule -a Alacritty          desktop='home' state=monocle  follow=on
bspc rule -a Kitty              desktop='home' state=monocle  follow=on
# Send to ref
bspc rule -a Zathura            desktop='ref'
# Send to dev
bspc rule -a Emacs              desktop='dev'  state=tiled follow=on
# Send to play
bspc rule -a Steam              desktop='play' follow=on
bspc rule -a bilibili           desktop='play' follow=on
# Send to note
bspc rule -a Logseq             desktop='note' follow=on
# Floating windows
bspc rule -a GoldenDict state=floating

# Use monocle layout on desktop 1
bspc desktop '^1' --layout monocle

# Border
bspc config focused_border_color        "#B48EAD"
bspc config normal_border_color         "#2e3440"
bspc config active_border_color         "#434c5e"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh dark&
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
nm-applet --indicator &
# Screenshot
## shutter &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

