#! /bin/sh
bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          36

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config active_border_color \#4c566a
bspc config normal_border_color \#4c566a
bspc config focused_border_color \#d8dee9

bspc config top_padding 48
bspc config left_padding 14
bspc config right_padding 14
bspc config bottom_padding 48

bspc config focus_follows_pointer true

## Rules
bspc rule -r '*:*'
bspc rule -a GoldenDict state=floating
bspc rule -a Zeal state=floating
bspc rule -a Anki state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a wechat.exe state=floating
bspc rule -a zoom state=floating
